name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test with Jekyll ${{ matrix.jekyll }} on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - jekyll: '~> 4.2'
            ruby: '3.1'
          - jekyll: '~> 4.2'
            ruby: '2.7'
          - jekyll: '~> 3.9'
            ruby: '2.7'
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: script/cibuild

  publish:
    name: Publish to RubyGems
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Publish to RubyGems
        run: |
          install -D -m 0600 /dev/null $HOME/.gem/credentials
          printf -- '---\n:rubygems_api_key: %s\n' "$RUBYGEMS_API_KEY" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
